# Generated by Django 6.0.3 on 2026-03-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField()),
                ('local', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('cancelado', 'Cancelado')], default='ativo', max_length=10)),
            ],
        ),
    ]
