# Generated by Django 6.0.3 on 2026-03-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='doador',
        ),
        migrations.AddField(
            model_name='donation',
            name='nome_doador',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
