# Generated by Django 6.0.3 on 2026-03-24 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('idade', models.PositiveIntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='animais/')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('adotado', 'Adotado')], default='disponivel', max_length=10)),
                ('adotante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
